# Generated by Django 4.2.2 on 2023-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificação', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('status', models.IntegerField(choices=[(0, 'Em análise'), (1, 'Aprovado'), (2, 'Reprovado')], default=0, max_length=1, verbose_name='Status Empréstimo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.IntegerField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=400, verbose_name='Endereço')),
                ('valorEmprestimo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Empréstimo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug Nome Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
