# Generated by Django 4.2.2 on 2023-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em análise'), (1, 'Aprovado'), (2, 'Reprovado')], default=0, verbose_name='Status Empréstimo'),
        ),
    ]
