# Generated by Django 4.2.2 on 2023-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emprestimo_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em análise'), (1, 'Aprovado'), (2, 'Negado')], default=0, verbose_name='Status Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valorEmprestimo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Empréstimo Pretendido'),
        ),
    ]
